create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null, age integer, weight numeric, height numeric, goal text, created_at timestamptz not null default now());
create table if not exists public.foods (id bigint generated by default as identity primary key, name text not null, calories numeric not null, protein numeric not null default 0, carbohydrates numeric not null default 0, fat numeric not null default 0, serving_size numeric not null default 100, created_at timestamptz not null default now());
create table if not exists public.meals (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, food_id bigint not null references public.foods(id), quantity numeric not null, meal_type text not null, date date not null default current_date, created_at timestamptz not null default now());

do $$ begin
	if not exists (select 1 from pg_constraint where conname = 'profiles_name_length') then alter table public.profiles add constraint profiles_name_length check (char_length(name) between 1 and 120); end if;
	if not exists (select 1 from pg_constraint where conname = 'profiles_age_valid') then alter table public.profiles add constraint profiles_age_valid check (age is null or age between 13 and 120); end if;
	if not exists (select 1 from pg_constraint where conname = 'profiles_weight_valid') then alter table public.profiles add constraint profiles_weight_valid check (weight is null or weight between 1 and 500); end if;
	if not exists (select 1 from pg_constraint where conname = 'profiles_height_valid') then alter table public.profiles add constraint profiles_height_valid check (height is null or height between 30 and 250); end if;
	if not exists (select 1 from pg_constraint where conname = 'foods_name_length') then alter table public.foods add constraint foods_name_length check (char_length(name) between 1 and 200); end if;
	if not exists (select 1 from pg_constraint where conname = 'foods_nutrition_valid') then alter table public.foods add constraint foods_nutrition_valid check (calories between 0 and 10000 and protein between 0 and 1000 and carbohydrates between 0 and 1000 and fat between 0 and 1000 and serving_size between 1 and 10000); end if;
	if not exists (select 1 from pg_constraint where conname = 'meals_quantity_valid') then alter table public.meals add constraint meals_quantity_valid check (quantity between 0.01 and 100000); end if;
	if not exists (select 1 from pg_constraint where conname = 'meals_type_valid') then alter table public.meals add constraint meals_type_valid check (meal_type in ('breakfast', 'lunch', 'snack', 'dinner')); end if;
end $$;

create index if not exists meals_user_date_idx on public.meals (user_id, date);
alter table public.profiles enable row level security;
alter table public.foods enable row level security;
alter table public.meals enable row level security;
drop policy if exists "Users manage own profile" on public.profiles;
drop policy if exists "Profiles select own" on public.profiles;
drop policy if exists "Profiles insert own" on public.profiles;
drop policy if exists "Profiles update own" on public.profiles;
drop policy if exists "Profiles delete own" on public.profiles;
create policy "Profiles select own" on public.profiles for select to authenticated using (auth.uid() = id);
create policy "Profiles insert own" on public.profiles for insert to authenticated with check (auth.uid() = id);
create policy "Profiles update own" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "Profiles delete own" on public.profiles for delete to authenticated using (auth.uid() = id);

drop policy if exists "Anyone can read foods" on public.foods;
create policy "Authenticated users read foods" on public.foods for select to authenticated using (true);

drop policy if exists "Users manage own meals" on public.meals;
drop policy if exists "Meals select own" on public.meals;
drop policy if exists "Meals insert own" on public.meals;
drop policy if exists "Meals update own" on public.meals;
drop policy if exists "Meals delete own" on public.meals;
create policy "Meals select own" on public.meals for select to authenticated using (auth.uid() = user_id);
create policy "Meals insert own" on public.meals for insert to authenticated with check (auth.uid() = user_id);
create policy "Meals update own" on public.meals for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Meals delete own" on public.meals for delete to authenticated using (auth.uid() = user_id);

-- Cria o perfil automaticamente durante o cadastro no Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
	insert into public.profiles (id, name)
	values (new.id, left(coalesce(nullif(new.raw_user_meta_data ->> 'name', ''), split_part(new.email, '@', 1), 'FitLab user'), 120));
	return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
	after insert on auth.users
	for each row execute procedure public.handle_new_user();

revoke all on function public.handle_new_user() from public, anon, authenticated;
