create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null, age integer, weight numeric, height numeric, goal text, created_at timestamptz not null default now());
create table public.foods (id bigint generated by default as identity primary key, name text not null, calories numeric not null, protein numeric not null default 0, carbohydrates numeric not null default 0, fat numeric not null default 0, serving_size numeric not null default 100, created_at timestamptz not null default now());
create table public.meals (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, food_id bigint not null references public.foods(id), quantity numeric not null, meal_type text not null, date date not null default current_date, created_at timestamptz not null default now());
alter table public.profiles enable row level security;
alter table public.foods enable row level security;
alter table public.meals enable row level security;
create policy "Users manage own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "Anyone can read foods" on public.foods for select using (true);
create policy "Users manage own meals" on public.meals for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
