-- NutriTrack — schema completo. Idempotente: pode ser executado novamente com segurança.
--
-- Modelo de alimentos:
--   foods.user_id is null  -> base nutricional compartilhada (somente leitura para o cliente)
--   foods.user_id = auth.uid() -> alimento criado pelo próprio usuário (ele edita e apaga)
-- Receitas são sempre privadas do usuário que as criou.

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null, age integer, weight numeric, height numeric, goal text, created_at timestamptz not null default now());
create table if not exists public.foods (id bigint generated by default as identity primary key, name text not null, calories numeric not null, protein numeric not null default 0, carbohydrates numeric not null default 0, fat numeric not null default 0, serving_size numeric not null default 100, base_unit text not null default 'g', portion_label text, portion_amount numeric, created_at timestamptz not null default now());
create table if not exists public.meals (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, food_id bigint not null references public.foods(id), quantity numeric not null, meal_type text not null, date date not null default current_date, created_at timestamptz not null default now());
create table if not exists public.recipes (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, name text not null, created_at timestamptz not null default now());
create table if not exists public.recipe_items (id bigint generated by default as identity primary key, recipe_id bigint not null references public.recipes(id) on delete cascade, food_id bigint not null references public.foods(id) on delete cascade, quantity numeric not null);
create table if not exists public.weight_logs (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, date date not null, weight_kg numeric not null, created_at timestamptz not null default now());
create table if not exists public.meal_slots (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, name text not null, icon text not null default 'utensils', position integer not null default 0, created_at timestamptz not null default now());

-- Perfil nutricional: mora em profiles, que já guardava idade, peso, altura e objetivo.
-- bmr, tdee e as metas são derivados dos demais campos e ficam gravados para o dashboard
-- ler sem recalcular. Não há histórico: cada recálculo substitui os valores anteriores.
alter table public.profiles add column if not exists sex text;
alter table public.profiles add column if not exists activity_level text;
alter table public.profiles add column if not exists bmr numeric;
alter table public.profiles add column if not exists tdee numeric;
alter table public.profiles add column if not exists target_calories numeric;
alter table public.profiles add column if not exists protein_g numeric;
alter table public.profiles add column if not exists carbs_g numeric;
alter table public.profiles add column if not exists fat_g numeric;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();
-- Peso-meta opcional do acompanhamento de peso. O peso usado nas metas continua em
-- profiles.weight; as pesagens do dia a dia ficam em weight_logs.
alter table public.profiles add column if not exists target_weight numeric;
-- Idioma da interface escolhido pelo usuário (acompanha a conta entre aparelhos).
alter table public.profiles add column if not exists language text;

-- As refeições do dia deixaram de ser quatro tipos fixos e passaram a apontar para uma
-- refeição criada pelo usuário (meal_slots). meal_type fica como coluna legada, sem uso:
-- vira opcional em vez de ser removida, para não descartar registro antigo de ninguém.
alter table public.meals add column if not exists slot_id bigint references public.meal_slots(id) on delete cascade;
alter table public.meals alter column meal_type drop not null;
alter table public.meals drop constraint if exists meals_type_valid;

-- Alimentos do usuário: null marca as linhas da base compartilhada.
alter table public.foods add column if not exists user_id uuid references auth.users(id) on delete cascade;
-- Nomes da base compartilhada em inglês e espanhol (só nomes; os valores são os mesmos).
-- Alimentos criados pelo usuário deixam estas colunas vazias e aparecem com o nome original.
alter table public.foods add column if not exists name_en text;
alter table public.foods add column if not exists name_es text;

-- Estas duas regras mudaram de definição (base 'un' e serving_size livre): remove para que o
-- bloco abaixo recrie com o texto atual. Sem isto, o "if not exists" manteria a versão antiga.
alter table public.foods drop constraint if exists foods_base_unit_valid;
alter table public.foods drop constraint if exists foods_nutrition_valid;

do $$ begin
	if not exists (select 1 from pg_constraint where conname = 'profiles_name_length') then alter table public.profiles add constraint profiles_name_length check (char_length(name) between 1 and 120); end if;
	if not exists (select 1 from pg_constraint where conname = 'profiles_age_valid') then alter table public.profiles add constraint profiles_age_valid check (age is null or age between 13 and 120); end if;
	if not exists (select 1 from pg_constraint where conname = 'profiles_weight_valid') then alter table public.profiles add constraint profiles_weight_valid check (weight is null or weight between 1 and 500); end if;
	if not exists (select 1 from pg_constraint where conname = 'profiles_height_valid') then alter table public.profiles add constraint profiles_height_valid check (height is null or height between 30 and 250); end if;
	if not exists (select 1 from pg_constraint where conname = 'profiles_sex_valid') then alter table public.profiles add constraint profiles_sex_valid check (sex is null or sex in ('male', 'female')); end if;
	if not exists (select 1 from pg_constraint where conname = 'profiles_activity_valid') then alter table public.profiles add constraint profiles_activity_valid check (activity_level is null or activity_level in ('sedentary', 'light', 'moderate', 'active', 'very_active')); end if;
	if not exists (select 1 from pg_constraint where conname = 'profiles_goal_valid') then alter table public.profiles add constraint profiles_goal_valid check (goal is null or goal in ('loss_light', 'loss_moderate', 'maintenance', 'gain_light', 'gain_moderate')); end if;
	-- Faixas de sanidade no banco: o cálculo vem do cliente, mas valor fora daqui não persiste.
	if not exists (select 1 from pg_constraint where conname = 'profiles_targets_valid') then alter table public.profiles add constraint profiles_targets_valid check ((bmr is null or bmr between 400 and 6000) and (tdee is null or tdee between 400 and 12000) and (target_calories is null or target_calories between 800 and 12000) and (protein_g is null or protein_g between 0 and 1000) and (carbs_g is null or carbs_g between 0 and 2000) and (fat_g is null or fat_g between 0 and 1000)); end if;
	if not exists (select 1 from pg_constraint where conname = 'profiles_language_valid') then alter table public.profiles add constraint profiles_language_valid check (language is null or language in ('pt', 'en', 'es')); end if;
	if not exists (select 1 from pg_constraint where conname = 'profiles_target_weight_valid') then alter table public.profiles add constraint profiles_target_weight_valid check (target_weight is null or target_weight between 30 and 300); end if;
	if not exists (select 1 from pg_constraint where conname = 'weight_logs_weight_valid') then alter table public.weight_logs add constraint weight_logs_weight_valid check (weight_kg between 30 and 300); end if;
	if not exists (select 1 from pg_constraint where conname = 'foods_translated_names_length') then alter table public.foods add constraint foods_translated_names_length check ((name_en is null or char_length(name_en) between 1 and 200) and (name_es is null or char_length(name_es) between 1 and 200)); end if;
	if not exists (select 1 from pg_constraint where conname = 'foods_name_length') then alter table public.foods add constraint foods_name_length check (char_length(name) between 1 and 200); end if;
	if not exists (select 1 from pg_constraint where conname = 'foods_nutrition_valid') then alter table public.foods add constraint foods_nutrition_valid check (calories between 0 and 10000 and protein between 0 and 1000 and carbohydrates between 0 and 1000 and fat between 0 and 1000 and serving_size between 0.1 and 10000); end if;
	if not exists (select 1 from pg_constraint where conname = 'foods_base_unit_valid') then alter table public.foods add constraint foods_base_unit_valid check (base_unit in ('g', 'ml', 'un')); end if;
	if not exists (select 1 from pg_constraint where conname = 'foods_portion_valid') then alter table public.foods add constraint foods_portion_valid check (portion_amount is null or portion_amount between 0.1 and 10000); end if;
	if not exists (select 1 from pg_constraint where conname = 'meals_quantity_valid') then alter table public.meals add constraint meals_quantity_valid check (quantity between 0.01 and 100000); end if;
	if not exists (select 1 from pg_constraint where conname = 'meal_slots_name_length') then alter table public.meal_slots add constraint meal_slots_name_length check (char_length(name) between 1 and 60); end if;
	-- O ícone é escolhido numa lista fechada: a interface desenha só estes.
	if not exists (select 1 from pg_constraint where conname = 'meal_slots_icon_valid') then alter table public.meal_slots add constraint meal_slots_icon_valid check (icon in ('sunrise', 'utensils', 'apple', 'moon', 'flame', 'bowl')); end if;
	if not exists (select 1 from pg_constraint where conname = 'meal_slots_position_valid') then alter table public.meal_slots add constraint meal_slots_position_valid check (position between 0 and 100); end if;
	if not exists (select 1 from pg_constraint where conname = 'recipes_name_length') then alter table public.recipes add constraint recipes_name_length check (char_length(name) between 1 and 120); end if;
	if not exists (select 1 from pg_constraint where conname = 'recipe_items_quantity_valid') then alter table public.recipe_items add constraint recipe_items_quantity_valid check (quantity between 0.01 and 100000); end if;
end $$;

create index if not exists meals_user_date_idx on public.meals (user_id, date);
create index if not exists foods_user_idx on public.foods (user_id);
create index if not exists recipes_user_idx on public.recipes (user_id);
create index if not exists recipe_items_recipe_idx on public.recipe_items (recipe_id);
create index if not exists meal_slots_user_idx on public.meal_slots (user_id, position);
create index if not exists meals_slot_idx on public.meals (slot_id);

-- Unicidade por escopo: a base compartilhada não repete nomes, e cada usuário não repete
-- nomes dentro da própria lista — mas nada impede dois usuários de criarem "Meu shake".
drop index if exists public.foods_name_unique_idx;
create unique index if not exists foods_shared_name_unique_idx on public.foods (lower(name)) where user_id is null;
create unique index if not exists foods_user_name_unique_idx on public.foods (user_id, lower(name)) where user_id is not null;
create unique index if not exists recipes_user_name_unique_idx on public.recipes (user_id, lower(name));
create unique index if not exists meal_slots_user_name_unique_idx on public.meal_slots (user_id, lower(name));
-- Uma pesagem por dia: registrar de novo no mesmo dia substitui o valor (upsert).
create unique index if not exists weight_logs_user_date_unique_idx on public.weight_logs (user_id, date);

alter table public.profiles enable row level security;
alter table public.foods enable row level security;
alter table public.meals enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_items enable row level security;
alter table public.meal_slots enable row level security;
alter table public.weight_logs enable row level security;

drop policy if exists "Users manage own profile" on public.profiles;
drop policy if exists "Profiles select own" on public.profiles;
drop policy if exists "Profiles insert own" on public.profiles;
drop policy if exists "Profiles update own" on public.profiles;
drop policy if exists "Profiles delete own" on public.profiles;
create policy "Profiles select own" on public.profiles for select to authenticated using (auth.uid() = id);
create policy "Profiles insert own" on public.profiles for insert to authenticated with check (auth.uid() = id);
create policy "Profiles update own" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "Profiles delete own" on public.profiles for delete to authenticated using (auth.uid() = id);

-- Leitura: base compartilhada + os próprios alimentos. Escrita: apenas os próprios.
-- "user_id = auth.uid()" nunca é verdadeiro para user_id null, então as linhas da base
-- compartilhada ficam fora de insert, update e delete do cliente, e o usuário também não
-- consegue publicar um alimento para todo mundo nem transferir um alimento para outra conta.
drop policy if exists "Anyone can read foods" on public.foods;
drop policy if exists "Authenticated users read foods" on public.foods;
drop policy if exists "Foods select shared or own" on public.foods;
drop policy if exists "Foods insert own" on public.foods;
drop policy if exists "Foods update own" on public.foods;
drop policy if exists "Foods delete own" on public.foods;
create policy "Foods select shared or own" on public.foods for select to authenticated using (user_id is null or user_id = auth.uid());
create policy "Foods insert own" on public.foods for insert to authenticated with check (user_id = auth.uid());
create policy "Foods update own" on public.foods for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Foods delete own" on public.foods for delete to authenticated using (user_id = auth.uid());

drop policy if exists "Users manage own meals" on public.meals;
drop policy if exists "Meals select own" on public.meals;
drop policy if exists "Meals insert own" on public.meals;
drop policy if exists "Meals update own" on public.meals;
drop policy if exists "Meals delete own" on public.meals;
create policy "Meals select own" on public.meals for select to authenticated using (auth.uid() = user_id);
create policy "Meals insert own" on public.meals for insert to authenticated with check (auth.uid() = user_id);
create policy "Meals update own" on public.meals for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Meals delete own" on public.meals for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Recipes select own" on public.recipes;
drop policy if exists "Recipes insert own" on public.recipes;
drop policy if exists "Recipes update own" on public.recipes;
drop policy if exists "Recipes delete own" on public.recipes;
create policy "Recipes select own" on public.recipes for select to authenticated using (auth.uid() = user_id);
create policy "Recipes insert own" on public.recipes for insert to authenticated with check (auth.uid() = user_id);
create policy "Recipes update own" on public.recipes for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Recipes delete own" on public.recipes for delete to authenticated using (auth.uid() = user_id);

-- Os itens herdam o dono da receita: sem receita própria, nenhuma linha é visível ou gravável.
drop policy if exists "Recipe items select own" on public.recipe_items;
drop policy if exists "Recipe items insert own" on public.recipe_items;
drop policy if exists "Recipe items update own" on public.recipe_items;
drop policy if exists "Recipe items delete own" on public.recipe_items;
create policy "Recipe items select own" on public.recipe_items for select to authenticated using (exists (select 1 from public.recipes r where r.id = recipe_id and r.user_id = auth.uid()));
create policy "Recipe items insert own" on public.recipe_items for insert to authenticated with check (exists (select 1 from public.recipes r where r.id = recipe_id and r.user_id = auth.uid()));
create policy "Recipe items update own" on public.recipe_items for update to authenticated using (exists (select 1 from public.recipes r where r.id = recipe_id and r.user_id = auth.uid())) with check (exists (select 1 from public.recipes r where r.id = recipe_id and r.user_id = auth.uid()));
create policy "Recipe items delete own" on public.recipe_items for delete to authenticated using (exists (select 1 from public.recipes r where r.id = recipe_id and r.user_id = auth.uid()));

drop policy if exists "Meal slots select own" on public.meal_slots;
drop policy if exists "Meal slots insert own" on public.meal_slots;
drop policy if exists "Meal slots update own" on public.meal_slots;
drop policy if exists "Meal slots delete own" on public.meal_slots;
create policy "Meal slots select own" on public.meal_slots for select to authenticated using (auth.uid() = user_id);
create policy "Meal slots insert own" on public.meal_slots for insert to authenticated with check (auth.uid() = user_id);
create policy "Meal slots update own" on public.meal_slots for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Meal slots delete own" on public.meal_slots for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Weight logs select own" on public.weight_logs;
drop policy if exists "Weight logs insert own" on public.weight_logs;
drop policy if exists "Weight logs update own" on public.weight_logs;
drop policy if exists "Weight logs delete own" on public.weight_logs;
create policy "Weight logs select own" on public.weight_logs for select to authenticated using (auth.uid() = user_id);
create policy "Weight logs insert own" on public.weight_logs for insert to authenticated with check (auth.uid() = user_id);
create policy "Weight logs update own" on public.weight_logs for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Weight logs delete own" on public.weight_logs for delete to authenticated using (auth.uid() = user_id);

-- Privilégios de tabela. A RLS decide QUAIS linhas o usuário vê; o grant decide se o role
-- pode tocar na tabela. Sem isto o PostgREST responde 42501 (permission denied) antes de
-- avaliar qualquer policy. Concedido apenas a authenticated: anon continua sem acesso.
-- foods recebe escrita porque o usuário cria os próprios alimentos; as policies acima são
-- o que impede qualquer escrita nas linhas da base compartilhada.
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.foods to authenticated;
grant select, insert, update, delete on public.meals to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.recipes to authenticated;
grant select, insert, update, delete on public.recipe_items to authenticated;
grant select, insert, update, delete on public.meal_slots to authenticated;
grant select, insert, update, delete on public.weight_logs to authenticated;

-- Cria o perfil automaticamente durante o cadastro no Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
	insert into public.profiles (id, name)
	values (new.id, left(coalesce(nullif(new.raw_user_meta_data ->> 'name', ''), split_part(new.email, '@', 1), 'NutriTrack user'), 120));
	return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
	after insert on auth.users
	for each row execute procedure public.handle_new_user();

revoke all on function public.handle_new_user() from public, anon, authenticated;
